### ISSUE TITLE
Improved CSS

### ISSUE THREAD

**Issue by renatofrota** [tberghuis/watch-and-read-comments-for-youtube#51]
Dark
![image](https://github.com/user-attachments/assets/0c78ff5f-9100-4819-9ef1-836b4ccfbb6f)

Light
![image](https://github.com/user-attachments/assets/5127ff02-3edc-45ad-81e4-013f1519d5dd)

("Description" is active and "Comments" on hover on both images)

```css
#primary .html5-video-player {
    background-color: var(--yt-spec-base-background);
}

#below {
    margin-top: -80px;
}

#warc-tab-headings {
    background-color: var(--yt-spec-base-background);
    padding: 10px 0;
    top: 50px;
}

#warc-tab-headings > button {
    border-radius: 8px;
    font-size: 14px;
    font-weight: 500;
    font-family: Roboto;
    text-transform: capitalize;
    padding: 8px 12px;
    margin-right: 8px;
    background-color: var(--yt-spec-badge-chip-background);
    color: var(--yt-spec-text-primary);
    cursor: pointer;
    border: none;
}

#warc-tab-headings > button:not(.active):hover,
#warc-tab-headings > button:not(.active):focus {
    background-color: var(--yt-spec-button-chip-background-hover);
}

#warc-tab-headings > button.active {
    background-color: var(--yt-spec-text-primary);
    color: var(--yt-spec-text-primary-inverse);
}
```

You can use an extension like [Stylus](https://chromewebstore.google.com/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) to apply or install the style automatically from [Userstyles.world](https://userstyles.world/style/18907/comments-sidebar-for-youtube-seamless-layout).

@tberghuis, feel free to use it on your extension, no © and no attribution is necessary.

--- after several edits ---

another option, more compact, buttons beside user menu.

Dark
![image](https://github.com/user-attachments/assets/334fce87-75e1-4ab7-be85-3c910b3f7792)

Light
![image](https://github.com/user-attachments/assets/00127319-17c7-4622-bd9a-2228c4be16f0)

```css
#center.ytd-masthead {
    position: absolute;
    left: 150px;
}

#primary .html5-video-player {
    background-color: var(--yt-spec-base-background);
}

ytd-watch-flexy[default-layout] #below {
    /* use -100px on narrow screens */
    margin-top: -125px;
}

#warc-resize-bar > div {
    background-color: transparent;
}

#warc-tab-headings {
    background-color: var(--yt-spec-base-background);
    padding: 4px 0;
    top: 0px;
    z-index: 2020;
}

#warc-tab-headings > button {
    border-radius: 8px;
    font-size: 14px;
    font-weight: 500;
    font-family: Roboto;
    text-transform: capitalize;
    padding: 8px 12px;
    margin: 8px 8px 0 0;
    background-color: var(--yt-spec-badge-chip-background);
    color: var(--yt-spec-text-primary);
    cursor: pointer;
    border: none;
}

#warc-tab-headings > button:not(.active):hover,
#warc-tab-headings > button:not(.active):focus {
    background-color: var(--yt-spec-button-chip-background-hover);
}

#warc-tab-headings > button.active {
    background-color: var(--yt-spec-text-primary);
    color: var(--yt-spec-text-primary-inverse);
}
```

If you want to translate the buttons:

```css
#warc-tab-headings > button {
    text-indent: -9999px;
    line-height: 0;
}

#warc-tab-headings > button::after {
    text-indent: 0;
    display: block;
    line-height: initial;
}

#warc-tab-headings > button:nth-child(1)::after {
    content: "Descrição";
}

#warc-tab-headings > button:nth-child(2)::after {
    content: "Comentários";
}

#warc-tab-headings > button:nth-child(3)::after {
    content: "Relacionados";
}

#warc-tab-headings > button:nth-child(4)::after {
    content: "Playlist";
}

#warc-tab-headings > button:nth-child(5)::after {
    content: "Chat";
}
```

**Comment by CyanSlinky** [comment]
Thank you very much for posting this, really makes the extension look native!

I did some slight modifications so that instead of text it's just icons and takes up very little space, and I also added tooltips.

<img width="283" height="85" alt="Image" src="https://github.com/user-attachments/assets/9353a257-b82c-452a-a4e3-5d0213b25363" />

```css
#center.ytd-masthead {
    position: absolute;
    left: 150px;
}

#background.ytd-masthead {
    opacity: 1 !important;
}

#primary .html5-video-player {
    background-color: var(--yt-spec-base-background);
}

ytd-watch-flexy[default-layout] #below {
    /* use -100px on narrow screens */
    margin-top: -125px;
}

#warc-resize-bar > div {
    background-color: transparent;
}

#warc-tab-headings {
    background-color: var(--yt-spec-base-background);
    padding: 4px 0;
    top: 0px;
    z-index: 2020;
}

#warc-tab-headings > button {
    border-radius: 50px;
    font-size: 14px;
    font-weight: 500;
    font-family: Roboto;
    text-transform: capitalize;
    padding: 8px 12px;
    margin: 8px 8px 0 0;
    background-color: var(--yt-spec-badge-chip-background);
    color: var(--yt-spec-text-primary);
    cursor: pointer;
    border: none;
}

#warc-tab-headings > button:not(.active):hover,
#warc-tab-headings > button:not(.active):focus {
    background-color: var(--yt-spec-button-chip-background-hover);
}

#warc-tab-headings > button.active {
    background-color: var(--yt-spec-text-primary);
    color: var(--yt-spec-text-primary-inverse);
}

#warc-tab-headings > button {
    text-indent: -9999px;
    line-height: 0;
    position: relative;
    overflow: visible !important;
}

#warc-tab-headings > button::after {
    text-indent: 0;
    display: block;
    line-height: initial;
}

#warc-tab-headings > button:nth-child(1)::after { content: "📝"; }
#warc-tab-headings > button:nth-child(2)::after { content: "🗨️"; }
#warc-tab-headings > button:nth-child(3)::after { content: "🎞️"; }
#warc-tab-headings > button:nth-child(4)::after { content: "📂"; }
#warc-tab-headings > button:nth-child(5)::after { content: "💬"; }

/* Base tooltip styles for all buttons */
#warc-tab-headings > button::before {
    position: absolute;
    top: 125%;
    left: 50%;
    transform: translateX(-50%);
    background: var(--yt-spec-raised-background);
    color: var(--yt-spec-text-primary);
    padding: 4px 8px;
    border-radius: 4px;
    font-size: 12px;
    white-space: nowrap;
    opacity: 0;
    pointer-events: none;
    transition: opacity 0.2s;
    z-index: 9999;

    display: block;
    text-indent: 0;
    line-height: normal;
}

/* Show tooltip when hovered */
#warc-tab-headings > button:hover::before {
    opacity: 1;
}

/* Tooltip text per button */
#warc-tab-headings > button:nth-child(1)::before { content: "Description"; }
#warc-tab-headings > button:nth-child(2)::before { content: "Comments"; }
#warc-tab-headings > button:nth-child(3)::before { content: "Related Videos"; }
#warc-tab-headings > button:nth-child(4)::before { content: "Playlist"; }
#warc-tab-headings > button:nth-child(5)::before { content: "Live Chat"; }
```

Now the only thing missing for me is for the sidebar to go below the player when viewing in a vertical aspect ratio on a portrait aspect-ratio monitor etc. I wonder if it's possible to achieve that somehow...
